### ISSUE TITLE
How to convert multiple files?

### ISSUE THREAD

**Issue by chrisderwahre** [Sergeanur/XboxADPCM#1]
Hey, how can i use more then 1 file at the time, like all files in a folder?

Greeting Chris.

**Comment by Sergeanur** [comment]
Hey, sorry for late reply, didn't see this until now.

You can do this by making a .bat file with this line and then execute it
`for %%a in (*.wav) do XboxADPCM.exe "%%a"`

**Comment by chrisderwahre** [comment]
Ok thank you!
